service: vese-valheim-bot
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: eu-north-1
  environment:
    DISCORD_PUBLIC_KEY: ${env:DISCORD_PUBLIC_KEY}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ec2:DescribeInstances'
          Resource: "*"
        - Effect: 'Allow'
          Action:
            - 'ec2:StartInstances'
          Resource: "*"
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: "*"
        
functions:
  valheim-discord-bot:
    handler: handler.lambda_handler
    timeout: 30
    events:
      - http:
          path: /
          method: post
          cors: true
  valheim-child-status:
    name: valheim-child-status
    timeout: 30
    handler: valheim_child_status.lambda_handler

plugins:
  - serverless-python-requirements
